name: abogabot
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/abogabot/assets/images/rectangle1.png
    - packages/abogabot/assets/images/rectangle3.png
    - packages/abogabot/assets/images/ellipse1.png
    - packages/abogabot/assets/images/ellipse2.png
    - packages/abogabot/assets/images/ellipse4.png
    - packages/abogabot/assets/images/vector.svg
    - packages/abogabot/assets/images/ellipse5.png
    - packages/abogabot/assets/images/ellipse6.png
    - packages/abogabot/assets/images/rectangle17.png
    - packages/abogabot/assets/images/vector2.svg
    - packages/abogabot/assets/images/vector3.svg
    - packages/abogabot/assets/images/vector4.svg
    - packages/abogabot/assets/images/vector5.svg
    - packages/abogabot/assets/images/vector6.svg
    - packages/abogabot/assets/images/vector7.svg
    - packages/abogabot/assets/images/rectangle4.png
    - packages/abogabot/assets/images/image3.png
    - packages/abogabot/assets/images/rectangle5.png
    - packages/abogabot/assets/images/ellipse3.png
    - packages/abogabot/assets/images/rectangle16.png
    - packages/abogabot/assets/images/image4.png
    - packages/abogabot/assets/images/ellipse7.png
    - packages/abogabot/assets/images/ellipse8.png
    - packages/abogabot/assets/images/polygon1.svg
